// Test 17: Asynchronous-assert / synchronous-deassert reset synchronizer.
// The async reset rst_a_n is generated by the user (or external POR)
// and asserted asynchronously. To deassert safely in clk_b's domain it
// passes through a 2-FF sync chain so the deassert edge is aligned with
// clk_b. This is the textbook reset-CDC primitive.
//
// Real-world reset-CDC checking is sometimes a tool's blind spot
// because the "data" is a reset signal, the "FFs" are special-purpose,
// and the synchronizer chain looks like data sync but feeds the
// reset port of downstream flops. svlens should still recognize the
// 2-FF chain as a proper synchronizer.
//
// Expected: 0 violations, 0 cautions, 0 infos, 0 crossings.
//
// Rationale: rst_a_n is an external async input port -- it is not driven
// by a flip-flop in another domain inside the design, so there is no
// FF-to-FF crossing to enumerate. The 2-FF chain is the right structure
// for safe deassert. This fixture's value is as a NO-FALSE-POSITIVE
// guard for the common reset-sync pattern.

module reset_synchronizer (
    input  logic clk_b,
    input  logic rst_a_n,    // async-asserted, may be from a different domain
    output logic rst_b_sync_n
);

    logic rst_sync_ff1, rst_sync_ff2;

    // Async-assert when rst_a_n drops; sync-deassert via the 2-FF chain.
    always_ff @(posedge clk_b or negedge rst_a_n) begin
        if (!rst_a_n) begin
            rst_sync_ff1 <= 1'b0;
            rst_sync_ff2 <= 1'b0;
        end else begin
            rst_sync_ff1 <= 1'b1;
            rst_sync_ff2 <= rst_sync_ff1;
        end
    end

    assign rst_b_sync_n = rst_sync_ff2;

endmodule
