// Test 18: Reset signal generated by a clk_a flip-flop and used as the
// async reset of a clk_b flip-flop. Unlike fixture 17 (external async
// reset), here the reset crosses an internal clock boundary, so a
// dedicated 2-FF reset synchronizer in clk_b's domain is required to
// align the deassert edge.
//
// Setup:
//   * rst_gen_q lives on clk_a -- driven by a halt request.
//   * rst_b_sync_ff1/ff2 are the 2-FF deassert chain in clk_b's domain.
//   * The downstream consumer u_consumer.q uses rst_b_sync_ff2 as its
//     async reset.
//
// Expected: 0 violations, 0 cautions, 1 INFO (rst_gen_q -> rst_b_sync_ff1
//           via 2-FF sync), 1 crossing.

module internal_reset_cdc (
    input  logic clk_a,
    input  logic clk_b,
    input  logic por_n,        // power-on async reset, top-level
    input  logic halt_req,
    output logic q_out
);

    // ---- clk_a domain: generate the reset request ----
    logic rst_gen_q;

    always_ff @(posedge clk_a or negedge por_n) begin
        if (!por_n)
            rst_gen_q <= 1'b1;        // active high during POR
        else
            rst_gen_q <= halt_req;
    end

    // ---- clk_b domain: 2-FF synchronizer for the cross-domain reset ----
    logic rst_b_sync_ff1, rst_b_sync_ff2;

    always_ff @(posedge clk_b or negedge por_n) begin
        if (!por_n) begin
            rst_b_sync_ff1 <= 1'b1;
            rst_b_sync_ff2 <= 1'b1;
        end else begin
            rst_b_sync_ff1 <= rst_gen_q;
            rst_b_sync_ff2 <= rst_b_sync_ff1;
        end
    end

    // ---- consumer: async-asserted by the synced reset ----
    logic consumer_q;

    always_ff @(posedge clk_b or negedge por_n) begin
        if (!por_n)
            consumer_q <= 1'b0;
        else if (rst_b_sync_ff2)
            consumer_q <= 1'b0;
        else
            consumer_q <= ~consumer_q;
    end

    assign q_out = consumer_q;

endmodule
